CREATE TABLE `commercial_district_seoul` (
  `key` int(11) NOT NULL AUTO_INCREMENT,
  `quarter` varchar(10) DEFAULT NULL,
  `code` varchar(7) DEFAULT NULL,
  `code_name` varchar(45) DEFAULT NULL,
  `total_count` bigint(24) DEFAULT NULL,
  `man_count` bigint(24) DEFAULT NULL,
  `woman_count` bigint(24) DEFAULT NULL,
  `age10_count` bigint(24) DEFAULT NULL,
  `age20_count` bigint(24) DEFAULT NULL,
  `age30_count` bigint(24) DEFAULT NULL,
  `age40_count` bigint(24) DEFAULT NULL,
  `age50_count` bigint(24) DEFAULT NULL,
  `age60_count` bigint(24) DEFAULT NULL,
  `time_00_06_count` bigint(24) DEFAULT NULL,
  `time_06_11_count` bigint(24) DEFAULT NULL,
  `time_11_14_count` bigint(24) DEFAULT NULL,
  `time_14_17_count` bigint(24) DEFAULT NULL,
  `time_17_21_count` bigint(24) DEFAULT NULL,
  `time_21_24_count` bigint(24) DEFAULT NULL,
  `monday_count` bigint(24) DEFAULT NULL,
  `tuesday_count` bigint(24) DEFAULT NULL,
  `wednesday_count` bigint(24) DEFAULT NULL,
  `thursday_count` bigint(24) DEFAULT NULL,
  `friday_count` bigint(24) DEFAULT NULL,
  `saturday_count` bigint(24) DEFAULT NULL,
  `sunday_count` bigint(24) DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`key`),
  UNIQUE KEY `idx_date_code` (`quarter`,`code`),
  KEY `idx_code` (`code`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=uca1400_ai_ci;

CREATE TABLE `district_foot_traffic` (
  `key` int(11) NOT NULL AUTO_INCREMENT,
  `quarter` varchar(10) DEFAULT NULL,
  `div_code` varchar(2) DEFAULT NULL,
  `div_code_name` varchar(45) DEFAULT NULL,
  `code` varchar(7) DEFAULT NULL,
  `code_name` varchar(45) DEFAULT NULL,
  `total_count` bigint(24) DEFAULT NULL,
  `man_count` bigint(24) DEFAULT NULL,
  `woman_count` bigint(24) DEFAULT NULL,
  `age10_count` bigint(24) DEFAULT NULL,
  `age20_count` bigint(24) DEFAULT NULL,
  `age30_count` bigint(24) DEFAULT NULL,
  `age40_count` bigint(24) DEFAULT NULL,
  `age50_count` bigint(24) DEFAULT NULL,
  `age60_count` bigint(24) DEFAULT NULL,
  `time_00_06_count` bigint(24) DEFAULT NULL,
  `time_06_11_count` bigint(24) DEFAULT NULL,
  `time_11_14_count` bigint(24) DEFAULT NULL,
  `time_14_17_count` bigint(24) DEFAULT NULL,
  `time_17_21_count` bigint(24) DEFAULT NULL,
  `time_21_24_count` bigint(24) DEFAULT NULL,
  `monday_count` bigint(24) DEFAULT NULL,
  `tuesday_count` bigint(24) DEFAULT NULL,
  `wednesday_count` bigint(24) DEFAULT NULL,
  `thursday_count` bigint(24) DEFAULT NULL,
  `friday_count` bigint(24) DEFAULT NULL,
  `saturday_count` bigint(24) DEFAULT NULL,
  `sunday_count` bigint(24) DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`key`),
  UNIQUE KEY `idx_date_code` (`quarter`,`code`),
  KEY `idx_code` (`code`),
  KEY `idx_quarter` (`quarter`)
) ENGINE=InnoDB AUTO_INCREMENT=223325 DEFAULT CHARSET=utf8mb4 COLLATE=uca1400_ai_ci

CREATE TABLE `district_foot_traffic_seoul` (
  `key` int(11) NOT NULL AUTO_INCREMENT,
  `quarter` varchar(10) DEFAULT NULL,
  `code` varchar(7) DEFAULT NULL,
  `code_name` varchar(45) DEFAULT NULL,
  `total_count` bigint(24) DEFAULT NULL,
  `man_count` bigint(24) DEFAULT NULL,
  `woman_count` bigint(24) DEFAULT NULL,
  `age10_count` bigint(24) DEFAULT NULL,
  `age20_count` bigint(24) DEFAULT NULL,
  `age30_count` bigint(24) DEFAULT NULL,
  `age40_count` bigint(24) DEFAULT NULL,
  `age50_count` bigint(24) DEFAULT NULL,
  `age60_count` bigint(24) DEFAULT NULL,
  `time_00_06_count` bigint(24) DEFAULT NULL,
  `time_06_11_count` bigint(24) DEFAULT NULL,
  `time_11_14_count` bigint(24) DEFAULT NULL,
  `time_14_17_count` bigint(24) DEFAULT NULL,
  `time_17_21_count` bigint(24) DEFAULT NULL,
  `time_21_24_count` bigint(24) DEFAULT NULL,
  `monday_count` bigint(24) DEFAULT NULL,
  `tuesday_count` bigint(24) DEFAULT NULL,
  `wednesday_count` bigint(24) DEFAULT NULL,
  `thursday_count` bigint(24) DEFAULT NULL,
  `friday_count` bigint(24) DEFAULT NULL,
  `saturday_count` bigint(24) DEFAULT NULL,
  `sunday_count` bigint(24) DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`key`),
  UNIQUE KEY `idx_date_code` (`quarter`,`code`),
  KEY `idx_code` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=82 DEFAULT CHARSET=utf8mb4 COLLATE=uca1400_ai_ci;

CREATE TABLE `district_office_workers` (
  `key` int(11) NOT NULL AUTO_INCREMENT,
  `quarter` varchar(10) DEFAULT NULL,
  `div_code` varchar(2) DEFAULT NULL,
  `div_code_name` varchar(45) DEFAULT NULL,
  `code` varchar(7) DEFAULT NULL,
  `code_name` varchar(45) DEFAULT NULL,
  `total_count` bigint(24) DEFAULT NULL,
  `man_count` bigint(24) DEFAULT NULL,
  `woman_count` bigint(24) DEFAULT NULL,
  `age10_count` bigint(24) DEFAULT NULL,
  `age20_count` bigint(24) DEFAULT NULL,
  `age30_count` bigint(24) DEFAULT NULL,
  `age40_count` bigint(24) DEFAULT NULL,
  `age50_count` bigint(24) DEFAULT NULL,
  `age60_count` bigint(24) DEFAULT NULL,
  `man_age10_count` bigint(24) DEFAULT NULL,
  `man_age20_count` bigint(24) DEFAULT NULL,
  `man_age30_count` bigint(24) DEFAULT NULL,
  `man_age40_count` bigint(24) DEFAULT NULL,
  `man_age50_count` bigint(24) DEFAULT NULL,
  `man_age60_count` bigint(24) DEFAULT NULL,
  `woman_age10_count` bigint(24) DEFAULT NULL,
  `woman_age20_count` bigint(24) DEFAULT NULL,
  `woman_age30_count` bigint(24) DEFAULT NULL,
  `woman_age40_count` bigint(24) DEFAULT NULL,
  `woman_age50_count` bigint(24) DEFAULT NULL,
  `woman_age60_count` bigint(24) DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`key`),
  UNIQUE KEY `idx_date_code` (`quarter`,`code`),
  KEY `idx_code` (`code`),
  KEY `idx_quarter` (`quarter`)
) ENGINE=InnoDB AUTO_INCREMENT=155320 DEFAULT CHARSET=utf8mb4 COLLATE=uca1400_ai_ci;

CREATE TABLE `district_polygon` (
  `code` varchar(7) NOT NULL,
  `code_name` varchar(45) DEFAULT NULL,
  `div_code` varchar(2) DEFAULT NULL,
  `div_code_name` varchar(45) DEFAULT NULL,
  `sigungu_code` varchar(5) DEFAULT NULL,
  `sigungu_name` varchar(10) DEFAULT NULL,
  `leg_dong_code` varchar(45) DEFAULT NULL,
  `leg_dong_name` varchar(45) DEFAULT NULL,
  `area` decimal(28,9) DEFAULT NULL,
  `lat` decimal(18,14) DEFAULT NULL,
  `lng` decimal(18,14) DEFAULT NULL,
  `polygon` geometry NOT NULL,
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`code`),
  SPATIAL KEY `idx_polygon` (`polygon`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=uca1400_ai_ci;


CREATE TABLE `district_resident` (
  `key` int(11) NOT NULL AUTO_INCREMENT,
  `quarter` varchar(10) DEFAULT NULL,
  `div_code` varchar(2) DEFAULT NULL,
  `div_code_name` varchar(45) DEFAULT NULL,
  `code` varchar(7) DEFAULT NULL,
  `code_name` varchar(45) DEFAULT NULL,
  `total_count` bigint(24) DEFAULT NULL,
  `man_count` bigint(24) DEFAULT NULL,
  `woman_count` bigint(24) DEFAULT NULL,
  `age10_count` bigint(24) DEFAULT NULL,
  `age20_count` bigint(24) DEFAULT NULL,
  `age30_count` bigint(24) DEFAULT NULL,
  `age40_count` bigint(24) DEFAULT NULL,
  `age50_count` bigint(24) DEFAULT NULL,
  `age60_count` bigint(24) DEFAULT NULL,
  `man_age10_count` bigint(24) DEFAULT NULL,
  `man_age20_count` bigint(24) DEFAULT NULL,
  `man_age30_count` bigint(24) DEFAULT NULL,
  `man_age40_count` bigint(24) DEFAULT NULL,
  `man_age50_count` bigint(24) DEFAULT NULL,
  `man_age60_count` bigint(24) DEFAULT NULL,
  `woman_age10_count` bigint(24) DEFAULT NULL,
  `woman_age20_count` bigint(24) DEFAULT NULL,
  `woman_age30_count` bigint(24) DEFAULT NULL,
  `woman_age40_count` bigint(24) DEFAULT NULL,
  `woman_age50_count` bigint(24) DEFAULT NULL,
  `woman_age60_count` bigint(24) DEFAULT NULL,
  `total_house_count` bigint(24) DEFAULT NULL,
  `apartment_count` bigint(24) DEFAULT NULL,
  `not_apartment_count` bigint(24) DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`key`),
  UNIQUE KEY `idx_date_code` (`quarter`,`code`),
  KEY `idx_code` (`code`),
  KEY `idx_quarter` (`quarter`)
) ENGINE=InnoDB AUTO_INCREMENT=149322 DEFAULT CHARSET=utf8mb4 COLLATE=uca1400_ai_ci;


CREATE TABLE `district_resident_alltime` (
  `key` int(11) NOT NULL AUTO_INCREMENT,
  `quarter` varchar(10) DEFAULT NULL,
  `div_code` varchar(2) DEFAULT NULL,
  `div_code_name` varchar(45) DEFAULT NULL,
  `code` varchar(7) DEFAULT NULL,
  `code_name` varchar(45) DEFAULT NULL,
  `total_count` bigint(24) DEFAULT NULL,
  `man_count` bigint(24) DEFAULT NULL,
  `woman_count` bigint(24) DEFAULT NULL,
  `age10_count` bigint(24) DEFAULT NULL,
  `age20_count` bigint(24) DEFAULT NULL,
  `age30_count` bigint(24) DEFAULT NULL,
  `age40_count` bigint(24) DEFAULT NULL,
  `age50_count` bigint(24) DEFAULT NULL,
  `age60_count` bigint(24) DEFAULT NULL,
  `man_age10_count` bigint(24) DEFAULT NULL,
  `man_age20_count` bigint(24) DEFAULT NULL,
  `man_age30_count` bigint(24) DEFAULT NULL,
  `man_age40_count` bigint(24) DEFAULT NULL,
  `man_age50_count` bigint(24) DEFAULT NULL,
  `man_age60_count` bigint(24) DEFAULT NULL,
  `woman_age10_count` bigint(24) DEFAULT NULL,
  `woman_age20_count` bigint(24) DEFAULT NULL,
  `woman_age30_count` bigint(24) DEFAULT NULL,
  `woman_age40_count` bigint(24) DEFAULT NULL,
  `woman_age50_count` bigint(24) DEFAULT NULL,
  `woman_age60_count` bigint(24) DEFAULT NULL,
  `total_house_count` bigint(24) DEFAULT NULL,
  `apartment_count` bigint(24) DEFAULT NULL,
  `not_apartment_count` bigint(24) DEFAULT NULL,
  `updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `created_at` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`key`),
  UNIQUE KEY `idx_date_code` (`quarter`,`code`),
  KEY `idx_code` (`code`),
  KEY `idx_quarter` (`quarter`)
) ENGINE=InnoDB AUTO_INCREMENT=93033 DEFAULT CHARSET=utf8mb4 COLLATE=uca1400_ai_ci;