CREATE TABLE `building_leg_headline` (
  `building_id` varchar(33) NOT NULL COMMENT '관리_건축물대장_PK',
  `leg_div_code` varchar(1) DEFAULT NULL COMMENT '대장_구분_코드',
  `leg_div_code_name` varchar(100) DEFAULT NULL COMMENT '대장_구분_코드_명',
  `leg_type_code` varchar(1) DEFAULT NULL COMMENT '대장_종류_코드',
  `leg_type_code_name` varchar(100) DEFAULT NULL COMMENT '대장_종류_코드_명',
  `site_loc` varchar(500) DEFAULT NULL COMMENT '대지_위치',
  `road_name_site_loc` varchar(400) DEFAULT NULL COMMENT '도로명_대지_위치',
  `building_name` varchar(100) DEFAULT NULL COMMENT '건물_명',
  `sigungu_code` varchar(5) DEFAULT NULL COMMENT '시군구_코드',
  `leg_dong_code` varchar(5) DEFAULT NULL COMMENT '법정동_코드',
  `site_div_code` varchar(1) DEFAULT NULL COMMENT '대지_구분_코드',
  `bun` varchar(4) DEFAULT NULL COMMENT '번',
  `ji` varchar(4) DEFAULT NULL COMMENT '지',
  `specialji_name` varchar(200) DEFAULT NULL COMMENT '특수지_명',
  `block` varchar(20) DEFAULT NULL COMMENT '블록',
  `lot` varchar(20) DEFAULT NULL COMMENT '로트',
  `rest_lot_count` decimal(5,0) DEFAULT NULL COMMENT '외필지_수',
  `new_road_code` varchar(12) DEFAULT NULL COMMENT '새주소_도로_코드',
  `new_leg_dong_code` varchar(5) DEFAULT NULL COMMENT '새주소_법정동_코드',
  `is_underground` varchar(1) DEFAULT NULL COMMENT '새주소_지상지하_코드',
  `new_building_main_num` decimal(5,0) DEFAULT NULL COMMENT '새주소_본_번',
  `new_building_sub_num` decimal(5,0) DEFAULT 0 COMMENT '새주소_부_번',
  `dong_name` varchar(100) DEFAULT NULL COMMENT '동_명',
  `main_sub_sep_code` char(1) DEFAULT NULL COMMENT '주_부속_구분_코드',
  `main_sub_sep_code_name` varchar(100) DEFAULT NULL COMMENT '주_부속_구분_코드_명',
  `land_area` decimal(19,9) DEFAULT NULL COMMENT '대지_면적(㎡)',
  `arch_area` decimal(19,9) DEFAULT NULL COMMENT '건축_면적(㎡)',
  `arch_land_ratio` decimal(19,9) DEFAULT NULL COMMENT '건폐_율(%)',
  `total_floor_area` decimal(19,9) DEFAULT NULL COMMENT '연면적(㎡)',
  `total_floor_area_ratio` decimal(19,9) DEFAULT NULL COMMENT '용적_률_산정_연면적(㎡)',
  `floor_area_ratio` decimal(19,9) DEFAULT NULL COMMENT '용적_률(%)',
  `structure_code` varchar(2) DEFAULT NULL COMMENT '구조_코드',
  `structure_code_name` varchar(100) DEFAULT NULL COMMENT '구조_코드_명',
  `structure_etc` varchar(500) DEFAULT NULL COMMENT '기타_구조',
  `main_usage_code` varchar(5) DEFAULT NULL COMMENT '주_용도_코드',
  `main_usage_code_name` varchar(100) DEFAULT NULL COMMENT '주_용도_코드_명',
  `etc_usage` varchar(500) DEFAULT NULL COMMENT '기타_용도',
  `roof_code` varchar(2) DEFAULT NULL COMMENT '지붕_코드',
  `roof_code_name` varchar(100) DEFAULT NULL COMMENT '지붕_코드_명',
  `etc_roof` varchar(500) DEFAULT NULL COMMENT '기타_지붕',
  `household_number` varchar(5) DEFAULT NULL COMMENT '세대_수(세대)',
  `family_number` varchar(5) DEFAULT NULL COMMENT '가구_수(가구)',
  `height` decimal(19,9) DEFAULT NULL COMMENT '높이(m)',
  `gnd_floor_number` varchar(5) DEFAULT NULL COMMENT '지상_층_수',
  `base_floor_number` varchar(5) DEFAULT NULL COMMENT '지하_층_수',
  `lift_number` varchar(5) DEFAULT NULL COMMENT '승용_승강기_수',
  `e_lift_number` varchar(5) DEFAULT NULL COMMENT '비상용_승강기_수',
  `sub_arch_number` varchar(5) DEFAULT NULL COMMENT '부속_건축물_수',
  `sub_arch_area` decimal(19,9) DEFAULT NULL COMMENT '부속_건축물_면적(㎡)',
  `total_dong_area` decimal(19,9) DEFAULT NULL COMMENT '총_동_연면적(㎡)',
  `indoor_mech_parking_number` varchar(6) DEFAULT NULL COMMENT '옥내_기계식_대수(대)',
  `indoor_mech_parking_area` decimal(19,9) DEFAULT NULL COMMENT '옥내_기계식_면적(㎡)',
  `outdoor_mech_parking_number` varchar(6) DEFAULT NULL COMMENT '옥외_기계식_대수(대)',
  `outdoor_mech_parking_area` decimal(19,9) DEFAULT NULL COMMENT '옥외_기계식_면적(㎡)',
  `indoor_self_parking_number` varchar(6) DEFAULT NULL COMMENT '옥내_자주식_대수(대)',
  `indoor_self_parking_area` decimal(19,9) DEFAULT NULL COMMENT '옥내_자주식_면적(㎡)',
  `outdoor_self_parking_number` varchar(6) DEFAULT NULL COMMENT '옥외_자주식_대수(대)',
  `outdoor_self_parking_area` decimal(19,9) DEFAULT NULL COMMENT '옥외_자주식_면적(㎡)',
  `permit_date` varchar(8) DEFAULT NULL COMMENT '허가_일',
  `start_date` varchar(8) DEFAULT NULL COMMENT '착공_일',
  `use_approval_date` varchar(8) DEFAULT NULL COMMENT '사용승인_일',
  `license_year` varchar(4) DEFAULT NULL COMMENT '허가번호_년',
  `license_agency_code` char(7) DEFAULT NULL COMMENT '허가번호_기관_코드',
  `license_agency_code_name` varchar(100) DEFAULT NULL COMMENT '허가번호_기관_코드_명',
  `license_div_code` varchar(4) DEFAULT NULL COMMENT '허가번호_구분_코드',
  `license_div_code_name` varchar(100) DEFAULT NULL COMMENT '허가번호_구분_코드_명',
  `unit_number` decimal(5,0) DEFAULT NULL COMMENT '호_수(호)',
  `energy_eff_grade` varchar(4) DEFAULT NULL COMMENT '에너지효율_등급',
  `energy_reduct_ratio` decimal(19,9) DEFAULT NULL COMMENT '에너지절감_율',
  `energy_epi_score` decimal(5,0) DEFAULT NULL COMMENT '에너지_EPI점수',
  `eco_arch_grade` char(1) DEFAULT NULL COMMENT '친환경_건축물_등급',
  `eco_arch_score` decimal(5,0) DEFAULT NULL COMMENT '친환경_건축물_인증점수',
  `intelligent_arch_grade` char(1) DEFAULT NULL COMMENT '지능형_건축물_등급',
  `intelligent_arch_score` decimal(5,0) DEFAULT NULL COMMENT '지능형_건축물_인증점수',
  `create_date` varchar(8) DEFAULT NULL COMMENT '생성_일자',
  `is_eq_resist` varchar(1) DEFAULT NULL COMMENT '내진_설계_적용_여부',
  `eq_resist_ability` varchar(200) DEFAULT NULL COMMENT '내진_능력',
  `leg_dong_code_val` varchar(10) DEFAULT NULL COMMENT 'concat(sigungu_code + leg_dong_code)',
  `update_date` datetime DEFAULT NULL,
  `insert_date` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`building_id`),
  KEY `idx_bun` (`bun`),
  KEY `idx_ji` (`ji`),
  KEY `idx_leg_dong_code_val` (`leg_dong_code_val`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=uca1400_ai_ci;

CREATE TABLE `building_floor_info` (
  `key` int(11) NOT NULL AUTO_INCREMENT,
  `building_id` varchar(33) DEFAULT NULL COMMENT '관리_건축물대장_PK',
  `site_loc` varchar(500) DEFAULT NULL COMMENT '대지_위치',
  `road_name_site_loc` varchar(400) DEFAULT NULL COMMENT '도로명_대지_위치',
  `building_name` varchar(100) DEFAULT NULL COMMENT '건물_명',
  `sigungu_code` varchar(5) DEFAULT NULL COMMENT '시군구_코드',
  `leg_dong_code` varchar(5) DEFAULT NULL COMMENT '법정동_코드',
  `site_div_code` varchar(1) DEFAULT NULL COMMENT '대지_구분_코드',
  `bun` varchar(4) DEFAULT NULL COMMENT '번',
  `ji` varchar(4) DEFAULT NULL COMMENT '지',
  `specialji_name` varchar(200) DEFAULT NULL COMMENT '특수지_명',
  `block` varchar(20) DEFAULT NULL COMMENT '블록',
  `lot` varchar(20) DEFAULT NULL COMMENT '로트',
  `new_road_code` varchar(12) DEFAULT NULL COMMENT '새주소_도로_코드',
  `new_leg_dong_code` varchar(5) DEFAULT NULL COMMENT '새주소_법정동_코드',
  `is_underground` varchar(1) DEFAULT NULL COMMENT '새주소_지상지하_코드',
  `new_building_main_num` decimal(5,0) DEFAULT NULL COMMENT '새주소_본_번',
  `new_building_sub_num` decimal(5,0) DEFAULT 0 COMMENT '새주소_부_번',
  `dong_name` varchar(100) DEFAULT NULL COMMENT '동_명',
  `floor_div_code` varchar(2) DEFAULT NULL COMMENT '층_구분_코드',
  `floor_div_code_name` varchar(100) DEFAULT NULL COMMENT '층_구분_코드명',
  `floor_number` decimal(4,0) DEFAULT NULL COMMENT '층_번호',
  `floor_number_name` varchar(100) DEFAULT NULL COMMENT '층_번호_명',
  `structure_code` varchar(2) DEFAULT NULL COMMENT '구조_코드',
  `structure_code_name` varchar(100) DEFAULT NULL COMMENT '구조_코드_명',
  `structure_etc` varchar(500) DEFAULT NULL COMMENT '기타_구조',
  `main_usage_code` varchar(5) DEFAULT NULL COMMENT '주_용도_코드',
  `main_usage_code_name` varchar(100) DEFAULT NULL COMMENT '주_용도_코드_명',
  `etc_usage` varchar(500) DEFAULT NULL COMMENT '기타_용도',
  `area` decimal(19,9) DEFAULT NULL COMMENT '면적',
  `main_sub_sep_code` char(1) DEFAULT NULL COMMENT '주_부속_구분_코드',
  `main_sub_sep_code_name` varchar(100) DEFAULT NULL COMMENT '주_부속_구분_코드_명',
  `is_except_area` varchar(1) DEFAULT NULL COMMENT '면적_제외_여부',
  `create_date` varchar(8) DEFAULT NULL COMMENT '생성_일자',
  `leg_dong_code_val` varchar(10) DEFAULT NULL,
  `update_date` datetime DEFAULT NULL,
  `insert_date` datetime DEFAULT current_timestamp(),
  PRIMARY KEY (`key`),
  KEY `idx_building_id` (`building_id`),
  KEY `idx_bun` (`bun`),
  KEY `idx_ji` (`ji`),
  KEY `idx_leg_dong_code_val` (`leg_dong_code_val`)
) ENGINE=InnoDB AUTO_INCREMENT=21089829 DEFAULT CHARSET=utf8mb4 COLLATE=uca1400_ai_ci;