

def update_building_leg_headline_query(data):
    return (f"INSERT INTO building_leg_headline ("
            f"building_id, leg_div_code, leg_div_code_name, leg_type_code, leg_type_code_name, "
            f"site_loc, road_name_site_loc, building_name, sigungu_code, leg_dong_code, "
            f"site_div_code, bun, ji, specialji_name, block, lot, rest_lot_count, "
            f"new_road_code, new_leg_dong_code, is_underground, new_building_main_num, "
            f"new_building_sub_num, dong_name, main_sub_sep_code, main_sub_sep_code_name, "
            f"land_area, arch_area, arch_land_ratio, total_floor_area, total_floor_area_ratio, "
            f"floor_area_ratio, structure_code, structure_code_name, structure_etc, "
            f"main_usage_code, main_usage_code_name, etc_usage, roof_code, roof_code_name, "
            f"etc_roof, household_number, family_number, height, gnd_floor_number, "
            f"base_floor_number, lift_number, e_lift_number, sub_arch_number, "
            f"sub_arch_area, total_dong_area, indoor_mech_parking_number, indoor_mech_parking_area, "
            f"outdoor_mech_parking_number, outdoor_mech_parking_area, indoor_self_parking_number, "
            f"indoor_self_parking_area, outdoor_self_parking_number, outdoor_self_parking_area, "
            f"permit_date, start_date, use_approval_date, license_year, "
            f"license_agency_code, license_agency_code_name, license_div_code, license_div_code_name, "
            f"unit_number, energy_eff_grade, energy_reduct_ratio, energy_epi_score, "
            f"eco_arch_grade, eco_arch_score, intelligent_arch_grade, intelligent_arch_score, "
            f"create_date, is_eq_resist, eq_resist_ability, leg_dong_code_val"
            f") VALUES ("
            f"'{data[0]}', '{data[1]}', '{data[2]}', '{data[3]}', '{data[4]}', "
            f"'{data[5]}', '{data[6]}', '{data[7]}', '{data[8]}', '{data[9]}', "
            f"'{data[10]}', '{data[11]}', '{data[12]}', '{data[13]}', '{data[14]}', '{data[15]}', {data[16]}, "
            f"'{data[17]}', '{data[18]}', '{data[19]}', {data[20]}, "
            f"{data[21]}, '{data[22]}', '{data[23]}', '{data[24]}',"
            f"{data[25]}, {data[26]}, {data[27]}, {data[28]}, {data[29]}, {data[30]}, "
            f"'{data[31]}', '{data[32]}', '{data[33]}', '{data[34]}', '{data[35]}', "
            f"'{data[36]}', '{data[37]}', '{data[38]}', '{data[39]}', '{data[40]}', "
            f"'{data[41]}', '{data[42]}', '{data[43]}', '{data[44]}', '{data[45]}', "
            f"'{data[46]}', '{data[47]}', '{data[48]}', '{data[49]}', '{data[50]}', "
            f"'{data[51]}', '{data[52]}', '{data[53]}', '{data[54]}', '{data[55]}', "
            f"'{data[56]}', '{data[57]}', '{data[58]}', '{data[59]}', '{data[60]}', "
            f"'{data[61]}', '{data[62]}', '{data[63]}', '{data[64]}', '{data[65]}', "
            f"'{data[66]}', '{data[67]}', '{data[68]}', '{data[69]}', '{data[70]}', " 
            f"'{data[71]}', '{data[72]}', '{data[73]}', '{data[74]}', '{data[75]}', '{data[76]}', '{data[8]}{data[9]}'"
            f") ON DUPLICATE KEY UPDATE "
            f"building_id = '{data[0]}', leg_div_code = '{data[1]}', leg_div_code_name = '{data[2]}', "
            f"leg_type_code = '{data[3]}', leg_type_code_name = '{data[4]}', site_loc = '{data[5]}', "
            f"road_name_site_loc = '{data[6]}', building_name = '{data[7]}', sigungu_code = '{data[8]}', "
            f"leg_dong_code = '{data[9]}', site_div_code = '{data[10]}', bun = '{data[11]}', ji = '{data[12]}', "
            f"specialji_name = '{data[13]}', block = '{data[14]}', lot = '{data[15]}', rest_lot_count = {data[16]}, "
            f"new_road_code = '{data[17]}', new_leg_dong_code = '{data[18]}', is_underground = '{data[19]}', "
            f"new_building_main_num = {data[20]}, new_building_sub_num = {data[21]}, dong_name = '{data[22]}', "
            f"main_sub_sep_code = '{data[23]}', main_sub_sep_code_name = '{data[24]}', land_area = {data[25]}, "
            f"arch_area = {data[26]}, arch_land_ratio = {data[27]}, total_floor_area = {data[28]}, "
            f"total_floor_area_ratio = {data[29]}, floor_area_ratio = {data[30]}, structure_code = '{data[31]}', "
            f"structure_code_name = '{data[32]}', structure_etc = '{data[33]}', main_usage_code = '{data[34]}', "
            f"main_usage_code_name = '{data[35]}', etc_usage = '{data[36]}', roof_code = '{data[37]}', "
            f"roof_code_name = '{data[38]}', etc_roof = '{data[39]}', household_number = '{data[40]}', "
            f"family_number = '{data[41]}', height = {data[42]}, gnd_floor_number = '{data[43]}', "
            f"base_floor_number = '{data[44]}', lift_number = '{data[45]}', e_lift_number = '{data[46]}', "
            f"sub_arch_number = '{data[47]}', sub_arch_area = {data[48]}, total_dong_area = {data[49]}, "
            f"indoor_mech_parking_number = '{data[50]}', indoor_mech_parking_area = {data[51]}, "
            f"outdoor_mech_parking_number = '{data[52]}', outdoor_mech_parking_area = {data[53]}, "
            f"indoor_self_parking_number = '{data[54]}', indoor_self_parking_area = {data[55]}, "
            f"outdoor_self_parking_number = '{data[56]}', outdoor_self_parking_area = {data[57]}, "
            f"permit_date = '{data[58]}', start_date = '{data[59]}', use_approval_date = '{data[60]}', "
            f"license_year = '{data[61]}', license_agency_code = '{data[62]}', license_agency_code_name = '{data[63]}', "
            f"license_div_code = '{data[64]}', license_div_code_name = '{data[65]}', unit_number = {data[66]}, "
            f"energy_eff_grade = '{data[67]}', energy_reduct_ratio = {data[68]}, energy_epi_score = {data[69]}, "
            f"eco_arch_grade = '{data[70]}', eco_arch_score = '{data[71]}', intelligent_arch_grade = '{data[72]}', "
            f"intelligent_arch_score = '{data[73]}', is_eq_resist = '{data[75]}', eq_resist_ability = '{data[76]}', "
            f"leg_dong_code_val = '{data[8]}{data[9]}'"
            )





